name: freud
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.1=openblas
  - bzip2=1.0.6=h470a237_2
  - ca-certificates=2018.4.16=0
  - certifi=2018.4.16=py36_0
  - clangdev=6.0.0=default_0
  - cmake=3.11.4=0
  - curl=7.60.0=0
  - cython=0.28.4=py36hfc679d8_0
  - expat=2.2.5=hfc679d8_1
  - icu=58.2=hfc679d8_0
  - krb5=1.14.6=0
  - libiconv=1.15=h470a237_1
  - libssh2=1.8.0=h5b517e9_2
  - libuv=1.20.3=0
  - libxml2=2.9.8=h422b904_2
  - llvm-meta=6.0.0=0
  - llvmdev=6.0.0=default_4
  - ncurses=5.9=10
  - numpy=1.14.5=py36_blas_openblashd3ea46f_201
  - openblas=0.2.20=8
  - openssl=1.0.2o=0
  - pip=9.0.3=py36_0
  - python=3.6.5=1
  - readline=7.0=0
  - rhash=1.3.4=0
  - scipy=1.1.0=py36_blas_openblashd3ea46f_201
  - setuptools=40.0.0=py36_0
  - sqlite=3.20.1=2
  - tbb=2018_20171205=0
  - tk=8.6.8=0
  - wheel=0.31.1=py36_0
  - xz=5.2.3=0
  - zlib=1.2.11=h470a237_3
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran=3.0.0=1
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - system=5.8=2
