name: freud
channels:
- conda-forge
- defaults
dependencies:
- blas=1.1=openblas
- bzip2=1.0.6=1
- ca-certificates=2017.11.5=0
- certifi=2017.11.5=py36_0
- clangdev=5.0.0=default_0
- cmake=3.10.0=4
- curl=7.55.1=0
- cython=0.27.3=py36_0
- expat=2.2.5=0
- icu=58.2=0
- krb5=1.14.2=0
- libiconv=1.15=0
- libssh2=1.8.0=2
- libuv=1.11.0=0
- libxml2=2.9.7=0
- llvmdev=5.0.0
- ncurses=5.9=10
- numpy=1.14.0=py36_blas_openblas_200
- openblas=0.2.20=7
- openssl=1.0.2n=0
- pip=9.0.1=py36_1
- python=3.6.4=0
- readline=7.0=0
- rhash=1.3.4=0
- scipy=1.0.0=py36_blas_openblas_201
- setuptools=38.4.0=py36_0
- sqlite=3.20.1=2
- tbb=2018_20171205=0
- tk=8.6.7=0
- wheel=0.30.0=py36_2
- xz=5.2.3=0
- zlib=1.2.11=0
- libgfortran=3.0.0=1
- system=5.8=2
