[workspace]
authors = ["Joshua A. Anderson <joaander@umich.edu>"]
channels = ["conda-forge"]
name = "freud"
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]

tbb = "*"
tbb-devel = "*"
ninja = "*"
cmake = "*"
gsd = "*"
matplotlib = "*"
nanobind = ">=2.0"
numpy = "*"
parsnip-cif = "*"
pillow = "*"
pytest = "*"
rowan = "*"
scikit-build-core = "*"
scipy = "*"
sympy = "*"
uv = "*"
sphinx-inline-tabs = "*"
bump-my-version = "*"

[feature.py312.dependencies]
python = "3.12.*"
[feature.py313.dependencies]
python = "3.13.*"
# [feature.py314.dependencies]
# python = "3.14.*"

[environments]
py312 = ["py312"]
py313 = ["py313"]
# py314 = ["py314"]
