name: Style check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger on pull requests.
  pull_request:

  # Trigger on pushes to main
  push:
    branches:
      - "main"

  # Trigger on request.
  workflow_dispatch:

jobs:
  clang-tidy:
    name: Check C++ Code Style
    runs-on: ubuntu-latest
    container:
      image: glotzerlab/ci:2021.11-clang10_py38
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          submodules: true
      - name: Install pre-commit
        run: python3 -m pip install pre-commit
      - name: Build freud and export compile commands
        run: |
          # glotzerlab ci containers do not come with scikit-build installed
          # this install can be removed once scikit-build is in the container
          python3 -m pip install scikit-build
          python3 setup.py build_ext --inplace -- -DCMAKE_EXPORT_COMPILE_COMMANDS=True
      - name: Execute clang-tidy and cppcheck
        run: |
          pre-commit run cppcheck --all-files --hook-stage=manual
          pre-commit run clang-tidy --all-files --hook-stage=manual
